### ISSUE TITLE
Auto Increment Version Number on merge?

### ISSUE THREAD

**Issue by mprice4-1Up** [SageMotionApps/020_Angle_Feedback_Test#7]
**Is your feature request related to a problem? Please describe.**
Can we use something like this to auto increment the version numbers? 
https://github.com/DianxinWang/bodynet/blob/f6157ff8567c2035da87f0704d4d7d8c1d323560/.github/workflows/master-merge-build.yml#L48C3-L98C33
@RTnhN

**Comment by RTnhN** [comment]
I think we need to be careful about bumping the version number. Right now, I think the version number is limited to 0_0 to 9_9 since the app id is 02000 or 02099.

**Comment by RTnhN** [comment]
Maybe we can just make that part of the PR template:

"Did you bump the version number appropriately?"
